<a href="/users">Пользователи</a>

<?php var_dump($user); ?>

<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<?php foreach ($user as $value) : ?>
<form action="/users/<?= $value['id'] ?>" method="post">
    <input type='hidden' name="_METHOD" value='PATCH'>
        <div>
            <label>
                Name
                <input type='text' name='user[nickname]' value="<?= $value['nickname'] ?? ''?>">
            </label>
            <?php if (isset($errors['nickname'])) : ?>
          <div><?= $errors['nickname'] ?></div>
            <?php endif ?> 
            <label>
                Email
                <input type='text' name='user[email]' value="<?= $value['email'] ?? ''?>">
            </label>

            <?php if (isset($errors['email'])) : ?>
                <div><?= $errors['email'] ?></div>
            <?php endif; ?>
        </div>
        <input type="submit" value='Update'>
</form>

<?php endforeach ?>