<a href="/users">Пользователи</a>

<?php if (count($flash) > 0) : ?>
    <ul>
    <?php foreach ($flash as $messages) : ?>
        <?php foreach ($messages as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach ?>
    <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/users" method="get">
    <input type="search" required name="search" value="<?= htmlspecialchars($search) ?>">
    <input type="submit" value="Search">
</form>

<table>
    <tr>
        <th>id</th>
        <th>first name</th>
    </tr>
  <?php foreach ($users as $user) : ?>
    <tr>
      <td>
          <a href="/users/<?= $user->id ?>"><?= $user->nickname ?></a>
      </td>
    </tr>
  <?php endforeach ?>
</table>
<br>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>