<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Пользователи</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link active" href="/users">Пользователи</a>
                <a class="nav-link" href="/users/new">Создать пользователя</a>
            </div>
        </div>
    </div>
</nav>

<?php if (count($flash) > 0) : ?>
    <ul>
        <?php foreach ($flash as $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <li><?= $message ?></li>
            <?php endforeach ?>
        <?php endforeach ?>
    </ul>
<?php endif ?>

<form action="/users" method="get">
    <input type="search" name="search" value="<?= htmlspecialchars($search) ?>">
    <input type="submit" value="Search">
</form>

<table>
    <tr>
        <th>id</th>
        <th>first name</th>
    </tr>
    <?php foreach ($users as $user) : ?>
        <tr>
            <td>
                <a href="/users/<?= $user['id']?>"><?= $user['id']?></a>
            </td>
            <td>
                <a href="/users/<?= $user['id']?>"><?= $user['nickname'] ?></a>
            </td>

            <td>
                <a href="/users/<?= $user['id']?>"><?= $user['email'] ?></a>
            </td>
        </tr>

    <?php endforeach ?>
</table>
<br>
<a href="?page=<?= $page < 2 ? 1 : $page - 1 ?>">Prev</a> <a href="?page=<?= $page + 1 ?>">Next</a>
</body>
</html>
