<form action="/users" method="post">
  <div>
    <label>
        Nickname
      <input type="text" name="user[nickname]" value="<?= htmlspecialchars($user['nickname']) ?>">
    </label>
    <?php if (isset($errors['nickname'])) : ?>
      <div><?= $errors['nickname'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email
      <input type="email" required name="user[email]" value="<?= htmlspecialchars($user['email']) ?>">
    </label>
    <?php if (isset($errors['email'])) : ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      id
      <input type="id" required name="user[id]" value="<?= htmlspecialchars($user['id']) ?>">
    </label>
    <?php if (isset($errors['id'])) : ?>
      <div><?= $errors['id'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Submit">
</form>