<form action="/users" method="post">

<?php var_dump($users); ?>


  <div>
    <label>
        Nickname
      <input type="text" name="user[nickname]" value="<?= htmlspecialchars($users['nickname']  ?? '') ?>">
    </label>
    <?php if (isset($errors['nickname'])) : ?>
      <div><?= $errors['nickname'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
        Email
      <input type="email" required name="user[email]" value="<?= htmlspecialchars($users['email'] ?? '') ?>">
    </label>
    <?php if (isset($errors['email'])) : ?>
      <div><?= $errors['email'] ?></div>
    <?php endif ?>
  </div>
  <div>
    <label>
      id
      <input type="id" required name="user[id]" value="<?= htmlspecialchars($users['id'] ?? '') ?>">
    </label>
    <?php if (isset($errors['id'])) : ?>
      <div><?= $errors['id'] ?></div>
    <?php endif ?>
  </div>
  <input type="submit" value="Submit">
</form>