<a href="/users">Пользователи</a>

<p><?= htmlspecialchars($user->nickname) ?></p>
<table>
    <tr>
       <td>Email</td>
       <td> <?= htmlspecialchars($user->email) ?> </td>
    </tr>
    <tr>
       <td>id</td>
       <td> <?= htmlspecialchars($user->id) ?> </td>
    </tr>
</table>

</form>
  <form action="/users/<?= htmlspecialchars($user->id) ?>" method="post">
    <input hidden name="_METHOD" value="DELETE">
    <input type="submit" value="Delete user">
  </form>